[package]
name = "avr-device"
version = "0.7.0"

authors = ["Rahix <rahix@rahix.de>"]
edition = "2021"
description = "Register access crate for AVR microcontrollers"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Rahix/avr-device"
readme = "README.md"
keywords = ["avr", "arduino"]
categories = ["no-std", "embedded", "hardware-support"]

include = [
    "/src/**/*.rs",
    "/LICENSE-*",
    "/README.md",
    "/build.rs",
    "/patch/**/*.yaml",
    "/vendor/*.atdf",
    "/vendor/LICENSE",
    "/examples/**/src/*.rs"
]

[features]
device-selected = []
attiny3224 = ["device-selected"]
rt = ["avr-device-macros"]

critical-section = ["critical-section/restore-state-u8"]

default = ["critical-section"]

# Unfortunately, we can only build documentation for a subset of the supported
# MCUs on docs.rs.  If you think a very popular chip is missing from the list,
# feel free to add it here.

[dependencies]
bare-metal = "1.0.0"
vcell = "0.1.3"
cfg-if = "1.0.0"
ufmt = { version = "0.2.0", optional = true }
critical-section = { version = "1.2.0", optional = true }

[dependencies.avr-device-macros]
path = "macros/"
version = "=0.7.0"
optional = true

[build-dependencies]
svd2rust = { version = "=0.37.0", default-features = false }
svdtools = { version = "=0.5.0", default-features = false }
atdf2svd = { version = "=0.5.1", default-features = false }
prettyplease = "=0.2.37"
svd-rs = { version = "=0.14.12", default-features = false }
yaml-rust2 = { version = "=0.10.2", default-features = false }
syn = { version = "=2.0.106", default-features = false, features = ["full", "parsing"] }
anyhow = "1.0"
